version: '3.0'

services:
   db:
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: innoventgate
      # MYSQL_USER: root
       MYSQL_ROOT_PASSWORD: password
       MYSQL_PASSWORD: password
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always

   sharaff-app:
     image: sharaff-app
     depends_on:
       - db
     build:
        context: "/home/sergio/ExitGateReportPanel/src/"
        dockerfile: Dockerfile
        args:
            - NODE_ENV=local
     ports:
       - "8080:5000"
       - "80:80"
       - "443:443"

volumes:
    dbdata: